### ISSUE TITLE
Test docker-to-singularity conversion directly through MLCube

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#412]

**Comment by hasan7n** [comment]
Works. Tested on `Ubuntu 22.04 LTS` with `Singularity 3.10.0` and `mlcube 0.0.8` and no docker installed.

Runner config in mlcube file:
```
singularity:
  image: mock-prep.simg
  build_file: docker://docker.synapse.org/syn51060790/mock-prep:0.0.0
  run_args: "-C --writable-tmpfs --net --network=none --nv"
```

where `docker://docker.synapse.org/syn51060790/mock-prep:0.0.0` is a private-access docker image on the Synapse docker registry. After setting the docker registry credentials according to [this link](https://singularity-userdoc.readthedocs.io/en/latest/singularity_and_docker.html#authentication-in-the-environment) (using the Synapse account credentials), the mlcube ran successfully (`mlcube configure --platform singularity`). It automatically used Singularity to build a SIF file from the specified docker image and placed it in the mlcube's workspace: `workspace/.image/mock-prep.simg`.
